#!/usr/bin/env bash
#
# Summary: Open qutebrowser in sandboxed mode
#
# Usage: {cmd} <name> [<extra args>]
#
# Create a new qutebrowser instance called `qutebrowser-<name>`. All extra
# arguments are passed to qutebrowser. The newly created window is brought into
# focus.
#
# If a window is already open for that session, just switch to it.

set -e

name="$1"
shift
extra="$@"

if [ -z "$name" ]; then
  dev help qutebrowser open
  exit 1
fi

# open app if it isn't already open
wid="$(wmctrl -l -x | grep qutebrowser-$name.qutebrowser | cut -d ' ' -f 1)"
if [ -z "$wid" ]; then
  qutebrowser-profile --new $name --qt-arg name qutebrowser-$name $extra
fi

# wait until client is created
while wid="$(wmctrl -l -x | grep qutebrowser-$name.qutebrowser | cut -d ' ' -f 1)"; [ -z "$wid" ]; do
  :
done

# switch to client tag and focus
awesome-client << LUA
  local awful = require("awful")

  local window = function (c)
    return awful.rules.match(c, { instance = "qutebrowser-$name"})
  end

  local screen = awful.screen.focused()

  for c in awful.client.iterate(window) do
    local tag = c.first_tag
    if tag then
       tag:view_only()
    end

    c:raise()

    c:emit_signal(
      "request::activate",
      "script",
      {raise = true}
    )

    break
  end
LUA
