#!/usr/bin/env bash
#
# Summary: Open a URL in qutebrowser as a new application
#
# Usage: {cmd} <name> <url>
#
# The URL is opened in a new qutebrowser window that uses a separate session.
# The window "instance" name will be `qutebrowser-<name>`.
#
# The client is then brought into focus.

set -e

name="$1"
url="$2"

if [ -z "$name" ]; then
  dev help qutebrowser open
  exit 1
fi

if [ -z "$url" ]; then
  dev help qutebrowser open
  exit 1
fi

# open app if it isn't already open
wid="$(wmctrl -l -x | grep qutebrowser-$name.qutebrowser | cut -d ' ' -f 1)"
if [ -z "$wid" ]; then
  qutebrowser-profile --new $name --qt-arg name qutebrowser-$name "$url"
fi

# wait until client is created
while wid="$(wmctrl -l -x | grep qutebrowser-$name.qutebrowser | cut -d ' ' -f 1)"; [ -z "$wid" ]; do
  :
done

# switch to client tag and focus
awesome-client << LUA
  local awful = require("awful")

  local window = function (c)
    return awful.rules.match(c, { instance = "qutebrowser-$name"})
  end

  local screen = awful.screen.focused()

  for c in awful.client.iterate(window) do
    local tag = c.first_tag
    if tag then
       tag:view_only()
    end

    c:raise()

    c:emit_signal(
      "request::activate",
      "script",
      {raise = true}
    )

    break
  end
LUA
