# brew
tap 'caskroom/cask'
brew 'brew-cask'

# base system
brew 'coreutils'
brew 'git'
brew 'htop-osx'

# tools
brew 'hub'
brew 'tmux'
brew 'the_silver_searcher'

# shell
brew 'zsh'
brew 'zsh-completions'

# development
brew 'pow'

# apps
cask 'google-chrome'
