#!/usr/bin/env bash
#
# Summary: Add an item to todoist
#
# Usage: {cmd} <item>

set -e

item="$(echo "" | dmenu)"

echo "$item"

dev todoist add "$item"
dev send-notification 0 "Todoist: Item Added" "$item"
