brew "coreutils"
brew "diff-so-fancy"
brew "fzf"
brew "git"
brew "hub"
brew "jq"
brew "neovim", args: ["HEAD"]
brew "rbenv"
brew "ripgrep"
brew "ruby-build"
brew "tmux"
brew "wget"
brew "zsh"

# Install Apps
cask "alfred3"
cask "caskroom/versions/firefox-developer-edition"
cask "docker"
cask "dropbox"
cask "homebrew/cask-fonts/font-source-code-pro"
cask "karabiner-elements"
cask "keepassxc"
cask "kitty"
cask "skype"
cask "slack"
cask "spectacle"
cask "spotify"
cask "the-unarchiver"
cask "whatsapp"
