tap "orf/brew"

brew "asdf"
brew "coreutils"
brew "ctags"
brew "diff-so-fancy"
brew "fzf"
brew "git"
brew "git-workspace"
brew "gpg"
brew "htop"
brew "hub"
brew "hyperfine"
brew "jq"
brew "libffi"
brew "libyaml"
brew "neovim", args: ["HEAD"]
brew "openssl"
brew "pandoc"
brew "rbenv"
brew "rbenv-default-gems"
brew "readline"
brew "ripgrep"
brew "ruby-build"
brew "tmux"
brew "wget"
brew "zsh"

# Install Apps
cask "alfred3"
cask "caskroom/versions/firefox-developer-edition"
cask "docker"
cask "drawio"
cask "dropbox"
cask "gimp"
cask "homebrew/cask-fonts/font-source-code-pro"
cask "java"
cask "karabiner-elements"
cask "keepassxc"
cask "kitty"
cask "macvim"
cask "skype"
cask "slack"
cask "spectacle"
cask "spotify"
cask "the-unarchiver"
cask "vlc"
cask "whatsapp"
