#!/usr/bin/env bash
#
# Summary: Take today as a sick day
#
# Usage: {cmd}

set -e

today="$(date '+%Y-%m-%d')"

curl \
  -u "${BAMBOO_TOKEN}:x" \
  --header "accept: application/json" \
  --header "content-type: application/json" \
  -X PUT \
  --data "{\"status\":\"requested\",\"start\":\"$today\",\"end\":\"$today\",\"amount\":\"1\",\"timeOffTypeId\":\"4\"}" \
  "https://api.bamboohr.com/api/gateway.php/${BAMBOO_SUBDOMAIN}/v1/employees/${BAMBOO_EMPLOYEE_ID}/time_off/request"
