#!/usr/bin/env bash
#
# Summary: Check failing dependabot PRs
#
# Usage: {cmd} <owner>

set -e

declare -A args="($_DEV_ARGS)"

gh search prs --checks=failure --state=open --owner=${args[owner]} --author=app/dependabot --archived=false -L 1000
