#!/usr/bin/env bash
#
# Summary: Check failing dependabot PRs
#
# Usage: {cmd} <owner>

set -e

owner="$1"

if [ -z "$owner" ]; then
  dev help dependabot failing
fi

gh search prs --checks=failure --state=open --owner=$owner --author=app/dependabot --archived=false -L 1000
