source $HOME/.vim/conf/plugins.vim

" Use modeline
set modeline
set modelines=2

" Use spaces instead of tabs
set expandtab
set smarttab
set tabstop=2
set shiftwidth=2

" Enable syntax highligh
syntax on

" Use filetype plugin
filetype off
filetype indent plugin on

" Disable swap files
set noswf

" Set the undo to have a thousand entries
set undolevels=1000

" Improve the search
set ignorecase smartcase showmatch hlsearch incsearch

" Add gems.tags to tags
set tags+=gems.tags

"colors
set t_Co=256
set background=light
colorscheme solarized

" gui options
if (has("gui_running"))
  " Remove all the UI cruft
  set go-=T
  set go-=l
  set go-=L
  set go-=r
  set go-=R

  function! s:initialize_font()
    if exists("&guifont")
      if has("mac")
        " Full screen means FULL screen
        set fuoptions=maxvert,maxhorz
        set guifont=Monaco:h14
      elseif has("unix")
        if &guifont == ""
          set guifont=bitstream\ vera\ sans\ mono\ 12
        endif
      elseif has("win32")
        set guifont=Consolas:h11,Courier\ New:h12
      endif
    endif
  endfunction

  augroup RCVisual
    autocmd!
    autocmd GUIEnter *  call s:initialize_font()
  augroup END
endif
