#!/usr/bin/env bash
#
# Summary: Prints AWS credentials from environment variables
#
# Usage: {cmd}
#
# This is just so I don't have to create a `~/.aws/credentials` file in plain
# text.
#
# https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html

set -e

cat <<JSON
{
  "Version": 1,
  "AccessKeyId": "$AWS_ACCESS_KEY_ID",
  "SecretAccessKey": "$AWS_SECRET_ACCESS_KEY"
}
JSON
