#!/usr/bin/env bash
#
# Summary: Implements the Rofi launcher
#
# Usage: {cmd} [text]
#
# Check `rofi-script` man page for details on the communication protocol.

set -e

print_top_level_option() {
  echo -en "\0data\x1ftoplevel\n"
  echo "dev"
}

print_config() {
  echo -en "\0no-custom\x1ftrue\n"
}

# First run
if [ "$ROFI_RETV" = "0" ]; then
  print_config
  print_top_level_option
  exit
fi

# Other runs

# get the argument
value="$@"

# exit if nothing was passed
if [ -z "$value" ]; then
  exit 0
fi

# top level option was chosen (can only be dev)
if [ "$ROFI_DATA" = "toplevel" ]; then
  echo -en "\0data\x1fcommand\n"
  dev commands rofi commands
  exit 0
fi

# command was chosen
if [ "$ROFI_DATA" = "command" ]; then
  command="$value"

  # run the command
  dev rofi commands "$command"

  exit
fi
