#!/usr/bin/env bash
#
# Summary: Implements the Rofi launcher
#
# Usage: {cmd} [text]
#
# Check `rofi-script` man page for details on the communication protocol.

set -e

print_top_level_options() {
  echo -en "bookmarks\0info\x1ftoplevel\n"
  echo -en "gh\0info\x1ftoplevel\n"
  echo -en "suspend\0info\x1ftoplevel\n"
  echo -en "single monitor\0info\x1ftoplevel\n"
  echo -en "dual monitor\0info\x1ftoplevel\n"
}

print_config() {
  echo -en "\0no-custom\x1ftrue\n"
}

# First run
if [ "$ROFI_RETV" = "0" ]; then
  print_config
  print_top_level_options
  rm -f "${_DEV_CACHE}/rofi-launcher-mode.txt"
  exit
fi

value="$@"
if [ -z "$value" ]; then
  exit 0
fi

# top level option was chosen
if [ "$ROFI_INFO" = "toplevel" ]; then
  echo "$value" > "${_DEV_CACHE}/rofi-launcher-mode.txt"

  if [ "$value" = "gh" ]; then
    if [ ! -e "${_DEV_CACHE}/github-repos.txt" ]; then
      dev github list-repos > "${_DEV_CACHE}/github-repos.txt"
    fi
    cat "${_DEV_CACHE}/github-repos.txt"
  fi

  if [ "$value" = "bookmarks" ]; then
    cat "${DOTFILES_HOME}/dotfiles/qutebrowser/.config/qutebrowser/bookmarks/urls"
    exit
  fi

  if [ "$value" = "suspend" ]; then
    dev power suspend
    exit
  fi

  if [ "$value" = "single monitor" ]; then
    xrandr --output DisplayPort-2 --off
    exit
  fi

  if [ "$value" = "dual monitor" ]; then
    xrandr --output HDMI-A-0 --auto --primary --output DisplayPort-2 --auto --scale 0.5x0.5 --right-of HDMI-A-0
    exit
  fi

  exit 0
fi

# argument was chosen
mode="$(cat "${_DEV_CACHE}/rofi-launcher-mode.txt")"

if [ "$mode" = "gh" ]; then
  xdg-open "https://github.com/$value"
fi

if [ "$mode" = "bookmarks" ]; then
  xdg-open "${value%% *}"
fi
