#!/usr/bin/env bash
#
# Summary: Open rofi launcher
#
# Usage: {cmd}

set -e

rofi \
  -show combi \
  -modi combi \
  -combi-modi ">:dev rofi _controller,window,run" \
  -matching fuzzy \
  -kb-accept-entry "Control+j,Control+m,Return,KP_Enter" \
  -sort true \
  -sorting-method fzf
