#!/usr/bin/env bash
#
# Summary: Open a Github repository in the browser using a fuzzy finder
#
# Usage: {cmd}

set -e

if [ ! -e "${_DEV_CACHE}/github-repos.txt" ]; then
  dev github list-repos > "${_DEV_CACHE}/github-repos.txt"
fi

repo="$(rofi -dmenu -matching fuzzy -p ">" -i -no-custom -input "${_DEV_CACHE}/github-repos.txt")"

xdg-open "https://github.com/$repo"
