#!/usr/bin/env bash
#
# Summary: SSH to a machine in opsworks
#
# Usage: {cmd} [<layer_id>]
#
# If no arguments are passed, chose the layer from a list.

set -e

layer_id="$1"

if [ -z "$layer_id" ]; then
  layer_id="$(dev aws opsworks list | sk | awk -F $'\t' '{print $3}')"
fi

if [ -z "$layer_id" ]; then
  exit 1
fi

ip="$(aws --region us-east-1 opsworks describe-instances --layer-id $layer_id | jq -r ".Instances | map(.PrivateIp) | .[]" | head -n 1)"

username="$(aws iam get-user | jq -r ".User.UserName")"

ssh $username@$ip
