#!/usr/bin/env bash
#
# Summary: Post a message to slack
#
# Usage: {cmd} <channel_id> <message>

set -e

channel_id="$1"
message="$2"

http \
  POST \
  "https://slack.com/api/chat.postMessage" \
  Authorization:"Bearer $SLACK_TOKEN" \
  channel="$channel_id" \
  text="$message"
