#!/usr/bin/env bash

set -e

gpg --export --armor 25CF925BEFF168CA3B21FA215DC9214C4F52F198 | gpg --symmetric --cipher-algo AES256 > ~/Sync/secrets/master.public.gpg
gpg --export-secret-keys --armor 25CF925BEFF168CA3B21FA215DC9214C4F52F198 | gpg --symmetric --cipher-algo AES256 > ~/Sync/secrets/master.secret.gpg
gpg --export-secret-subkeys --armor 25CF925BEFF168CA3B21FA215DC9214C4F52F198 | gpg --symmetric --cipher-algo AES256 > ~/Sync/secrets/master.signing.gpg
