#!/usr/bin/env bash

set -e

# import public key
echo "Importing public key"
gpg --decrypt ~/Sync/secrets/master.public.gpg | gpg --import

# import private key
echo "Importing private key"
gpg --decrypt ~/Sync/secrets/master.secret.gpg | gpg --import
