#!/usr/bin/env bash
#
# Summary: Decrypt and load secrets
#
# Usage: {cmd}

set -e

# Decrypt secrets file
gpg --decrypt "$HOME/Dropbox/secrets/zshrc.secret.asc" > "$DOTFILES_HOME/secrets/zshrc.secret"
