#!/usr/bin/env bash
#
# Summary: Encrypt and store secrets
#
# Usage: {cmd}

set -e

tar -cz -C "$DOTFILES_HOME" secrets | gpg --encrypt --sign --yes -r "$PERSONAL_EMAIL" --output "$HOME/Dropbox/secrets.gpg"
