#!/usr/bin/env bash
#
# Summary: Encrypt and store secrets
#
# Usage: {cmd}

set -e

# Encrypt secrets file
gpg --encrypt --sign --armor --yes -r "$PERSONAL_EMAIL" "$DOTFILES_HOME/secrets/zshrc.secret"

# Move it to Dropbox
mv "$DOTFILES_HOME/secrets/zshrc.secret.asc" "$HOME/Dropbox/secrets"
