#!/usr/bin/env bash
#
# Summary: Encrypt and store secrets
#
# Usage: {cmd}

set -e

tar -cz -C "$DOTFILES_HOME" secrets | gpg --symmetric --armor --output "$DOTFILES_HOME/assets/secrets.gpg" --cipher-algo AES256
