#!/usr/bin/env bash
#
# Summary: Add an item to todoist Inbox
#
# Usage: {cmd} <item>

set -e

item="$@"

usage() {
  dev help todoist add
}

if [ -z "$item" ]; then
  usage
  exit 1
fi

curl "https://api.todoist.com/rest/v1/tasks" \
    -X POST \
    --data "{\"content\": \"$item\", \"due_string\": \"today\", \"due_lang\": \"en\"}" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $TODOIST_TOKEN"
