#!/usr/bin/env bash
#
# Summary: Add an item to todoist Inbox
#
# Usage: {cmd} [item]...

set -e

item="$@"

curl "https://api.todoist.com/rest/v2/tasks" \
    -X POST \
    --data "{\"content\": \"$item\", \"due_string\": \"today\", \"due_lang\": \"en\"}" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $TODOIST_TOKEN"
