#!/usr/bin/env bash
#
# Summary: Clean up Nix store and boot entries
#
# Usage: {cmd}
#
# copied from: https://github.com/NixOS/nixpkgs/issues/3542

set -e

# remove old generations from system profile
sudo nix-env --delete-generations old --profile /nix/var/nix/profiles/system

# remove old generations from user profile
nix-env --delete-generations old

# reactivate current profile
sudo /nix/var/nix/profiles/system/bin/switch-to-configuration switch

# remove unused stuff in store (unfortunatly also removes dev stuff used by shell.nix)
sudo nix-store --gc
nix-store --gc
