#!/usr/bin/env bash
#
# Summary: Prepare a project for compiling with nix
#
# Usage: {cmd}

set -e

# Create direnv configuration
if [ ! -e ".envrc" ]; then
  echo use nix > .envrc
fi

# Create shell.nix
if [ ! -e "shell.nix" ]; then
  cat <<FILE_SHELLNIX > shell.nix
{ pkgs ? import <nixpkgs> {} }:
  pkgs.mkShell {
    nativeBuildInputs = with pkgs; [];
}
FILE_SHELLNIX
fi
