#!/usr/bin/env bash
#
# Summary: Search and install nix packages with fzf
#
# Usage: {cmd}

set -e

CACHE_FILE="${_DEV_CACHE}/nix-search-cache.txt"

if [ ! -e "$CACHE_FILE" ]; then
  nix-env -qa > "$CACHE_FILE"
fi

package="$(cat "$CACHE_FILE" | fzf)"

nix-env --install "$package"
