#!/usr/bin/env bash
#
# Summary: Switch NixOS to new config
#
# Usage: {cmd}

set -e

if [ "$(uname -s)" = "Darwin" ]; then
  darwin-rebuild switch --flake $DOTFILES_HOME
else
  sudo nixos-rebuild switch
fi
