#!/usr/bin/env bash
#
# Summary: Upgrade NixOS and reboot
#
# Usage: {cmd}
#
# This command doesn't update the system anymore because channels are ignored
# when using flakes. Instead I use `nix flake update` inside assets/nix to
# update the lockfile.

set -e

dev nix cleanup

sudo nixos-rebuild switch --upgrade

dev send-notification 0 "Rebooting" now

sleep 5

reboot
