#!/usr/bin/env bash
#
# Summary: Change default sink
#
# Usage: <cmd> <sink-name>

sink_name="$1"

if [ -z "$sink_name" ]; then
  dev help audio switch-sink
  exit 1
fi

# Check whether there are actually multiple cards available
totalsc=$(pacmd "list-sinks" | grep card: | wc -l)
if [ $totalsc -le 1 ]; then
  notify-send -u critical -t 5000 "Nothing to switch, system only has one sound card."
  exit
fi

# switch default sound card to chosen one
pacmd set-default-sink "$sink_name"

# $inputs: A list of currently playing inputs
inputs=$(pacmd list-sink-inputs | awk '$1 == "index:" {print $2}')
for INPUT in $inputs; do # Move all current inputs to the new default sound card
  pacmd move-sink-input $INPUT $sink_name
done
