theme = "solarized_dark"

[editor]
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
V = ["select_mode", "select_line_below"]
H = ["select_mode", "goto_line_start", "exit_select_mode"]
L = ["select_mode", "goto_line_end", "exit_select_mode"]

[keys.select]
j = ["select_line_below"]
k = ["select_line_above"]

[keys.normal.space]
w = ":write"
