#!/usr/bin/env bash
#
# Summary: Display the status of the latest build on travis for the current branch
#
# Usage: {cmd}

set -e

url=https://api.travis-ci.com
repo="$(dev github repo)"
encoded_repo="$(codon "$repo")"
branch="$(git branch --show-current)"

curl --silent -H "Travis-API-Version: 3" -H "Authorization: token $TRAVIS_TOKEN" "${url}/repo/${encoded_repo}/branch/${branch}" | jq "."
