export FZF_DEFAULT_COMMAND="rg --hidden --files -g '!.git'"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# Generated by fzf

# Key bindings
# ------------
#source "/usr/local/opt/fzf/shell/key-bindings.zsh"
