#!/usr/bin/env bash
#
# Summary: Opens a tmux session with Digital Garden
#
# Usage: {cmd}

set -e

# Include runtime tmux functions
source "${_DEV_ROOT}/lib/tmux.sh"

# Change into the DigitalGarden directory
cd ~/Sync/DigitalGarden

# Create the DigitalGarden session
if initialize_session "digitalgarden"; then
  # start editor
  new_window "notes"
  run_cmd "$EDITOR"

  # open index
  send_keys ":GorgOpenFile index.md"
  send_keys "C-m"

  # start services
  new_window "services"
  run_cmd "devenv up"

  select_window 1
fi
finalize_and_go_to_session
