#!/usr/bin/env bash
#
# Summary: Display tmux command launcher and run selected command
#
# Usage: {cmd}
#
# Press the associated letter to run the tmux command.

set -e

args=(
  "maximize current pane" "z" "resize-pane -Z"
  "last window" "Space" "last-window"
  "choose session" "S" "choose-session -N"
  "show keybindings" "?" "display-popup -E -w 80% -h 80% 'tmux list-keys -Na | fzf --reverse'"
  "switch session" "s" "run-shell -b 'dev tmux switch'"
  "open URL" "u" "run-shell -b 'dev tmux open-url'"
)

tmux display-menu -T "Commands" "${args[@]}"
