#!/usr/bin/env bash
#
# Summary: Prints the socket name for an nvim instance running in the first pane of current session
#
# Usage: {cmd}

set -e

# Get the tty of the first pane
pane_tty="$(tmux list-panes -s -F "#{pane_tty}" | head -1)"

# get the last pid on this pane
last_pid="$(ps -o pid -t "$pane_tty" | tail -1 | xargs)"

# assuming last_pid is the nvim instance, get a child pid
child_pid="$(pgrep -P $last_pid)"

# print the socket name
echo "/run/user/1000/nvim.${child_pid}.0"
