#!/usr/bin/env bash
#
# Summary: Prints the socket name for an nvim instance running in the current directory
#
# Usage: {cmd}

set -e

cwd_hash=$(echo -n "$PWD" | md5)
socket_path="/tmp/nvim.$cwd_hash"

echo "$socket_path"
