#!/usr/bin/env bash
#
# Summary: Open tmux session with a fuzzy finder
#
# Usage: {cmd}

set -e

selected="$(dev list | fzf --popup center,90%,90% --reverse --preview 'dev preview {}')" || exit 0

if [ -n "$selected" ]; then
  dev open "$selected"
fi
