#!/usr/bin/env bash
#
# Summary: Opens the org tmux session
#
# Usage: {cmd}

set -e

# Include runtime tmux functions
source "${_DEV_ROOT}/lib/tmux.sh"

# Change into org directory
if [ "$(uname -s)" = "Darwin" ]; then
  cd ~/Library/CloudStorage/Dropbox/org
else
  cd ~/Dropbox/org
fi

# Create org session
if initialize_session "org"; then
    new_window "editor"
    run_cmd "$EDITOR"

    # Open org index
    send_keys ":GorgOpenFile index.md"
    send_keys "C-m"
fi
finalize_and_go_to_session
