#!/usr/bin/env bash
#
# Summary: Opens the org tmux session
#
# Usage: {cmd}

set -e

# Include runtime tmux functions
source "${_DEV_ROOT}/lib/tmux.sh"

# Change into org directory
cd ~/Dropbox/org

# Create org session
if initialize_session "org"; then
    new_window "editor"
    run_cmd "$EDITOR"
fi
finalize_and_go_to_session
