#!/usr/bin/env bash
#
# Summary: Opens the runner tmux session
#
# Usage: {cmd}

set -e

# Include runtime tmux functions
source "${_DEV_ROOT}/lib/tmux.sh"

# Change into HOME directory
cd

# Create runner session
if initialize_session "runner"; then
  new_window "home"
fi
finalize
switch_to_session "runner"
