#!/usr/bin/env bash
#
# Summary: Open a popup to add a quick todo for the current project
#
# Usage: {cmd}
#
# Opens a tmux popup with a styled input field. The todo is saved
# to the vault under a section for the current working directory.

set -e

tmux display-popup -E -w 60% -h 5 "todo=\$(gum input --placeholder 'Add a todo...' --width 0); rc=\$?; [ \$rc -ne 0 ] && exit 0; [ -n \"\$todo\" ] && dev notes todo \"\$todo\"; exit 0"
