export ZSH_HOME="$HOME/.dotfiles/zsh"

ZSH_USE_TMUX=true
ZSH_PLUGINS=all
ZSH_THEME=default

# Overwrites the time to run the notification function for the time-tracker plugin
#TIME_TO_NOTIFY=30

# editor
export EDITOR=vi

source $ZSH_HOME/zshrc.sh
