#!/usr/bin/env bash
#
# Summary: Display an icon according to the current status of the current working directory
#
# Usage: {cmd}

set -e

if output=$(git status --porcelain) && [ -z "$output" ]; then
  # Working directory clean
  echo "🟢"
else
  # Uncommitted changes
  echo "🔴"
fi
