#!/usr/bin/env bash

set -e

if [[ "$QUTE_URL" =~ https:\/\/github.com\/([^/]*\/[^/]*) ]]; then
  name="${BASH_REMATCH[1]}"
else
  echo message-info \"Repository name not found\" > "$QUTE_FIFO"
  exit
fi

echo message-info \"Name: "$name"\" > "$QUTE_FIFO"

echo open -t "https://deploy.babbel.com/$name" > "$QUTE_FIFO"
