#!/usr/bin/env bash
#
# Summary: Explain text on the screen
#
# Allows you to select a part of the screen, reads text from it and asks ChatGPT to explain it.

set -e

# create an temporary image file
imagefile="$(mktemp -t image.XXXXXXXX).png"

# create a temporary text file
# tesseract takes this path and adds an extension .txt
textfile="$(mktemp -t text.XXXXXXXX)"

# capture an area of the screen
sel=$(slop -f "-i %i -g %g")
shotgun $sel "$imagefile"

# read the text from the image
tesseract "$imagefile" "$textfile" 2>/dev/null

# display the text
cat "$textfile".txt | sgpt "Explain this" | zenity --text-info --title="Read Screen"

# remove temporary files
rm "$imagefile"
rm "$textfile".txt
