#!/usr/bin/env bash
#
# Summary: Start working on the Github repository currently opened in Vivaldi

set -e

# create an temporary image file
imagefile="$(mktemp -t image.XXXXXXXX).png"

# create a temporary text file
# tesseract takes this path and adds an extension .txt
textfile="$(mktemp -t text.XXXXXXXX)"

# capture the URL on vivaldi
shotgun -i 1354 -g 1993x23+218+81 "$imagefile"

# read the URL from the image
tesseract "$imagefile" "$textfile" 2>/dev/null

# start a dev session with the URL
cat "$textfile".txt | xargs dev start

# remove temporary files
rm "$imagefile"
rm "$textfile".txt
