name: "Build mini system"

on:
  push:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Install Nix"
        uses: cachix/install-nix-action@v29
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: "accept-flake-config = true"

      - uses: cachix/cachix-action@v15
        with:
          name: juanibiapina
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: "Build mini configuration"
        run: "nix build .#nixosConfigurations.mini.config.system.build.toplevel"
