#!/usr/bin/env bash
#
# Summary: Reset current directory for development.
#
# Usage: {cmd}

set -e

git fetch --prune --tags

if git rev-parse --verify "origin/main" &>/dev/null; then
  BRANCH="main"
elif git rev-parse --verify "origin/published" &>/dev/null; then
  BRANCH="published"
else
  BRANCH="master"
fi

git clean -fd
git checkout $BRANCH
git clean-branches
git pull --rebase
