#!/usr/bin/env bash
#
# Summary: Opens a tmux session with Digital Garden
#
# Usage: {cmd}

set -e

# Change into the DigitalGarden directory
cd ~/Dropbox/DigitalGarden

nvim -c ":GorgOpenFile index.md"
