#!/usr/bin/env bash
#
# Summary: Rebase current branch with either origin/develop, origin/main
# or origin/master
#
# Usage: {cmd}

set -e

git fetch

if git rev-parse --verify "origin/main" &>/dev/null; then
  BRANCH="origin/main"
elif git rev-parse --verify "origin/published" &>/dev/null; then
  BRANCH="origin/published"
else
  BRANCH="origin/master"
fi

git rebase "$BRANCH"
