#!/usr/bin/env bash
#
# Summary: Link a binary to ~/bin
#
# Usage: {cmd} <file>

set -e

arg="$1"

target="$(realpath ${arg})"
name="${arg##*/}"

mkdir -p "$HOME/bin"
ln -s "${target}" "$HOME/bin/${name}"
