#!/usr/bin/env bash
#
# Summary: Lists local projects

set -e

# List directories exactly two levels deep inside the workspace
for name in $WORKSPACE/*/*; do
  if [[ -d "$name" ]]; then
    echo ${name#"$WORKSPACE/"}
  fi
done
