#!/usr/bin/env bash
#
# Summary: Manage a file as part of my dotfiles
#
# Usage: {cmd} <module> <file>
# Options:
#   module (script): The name of the program the file is part of
#   file: The file to manage
#
# Move <file> to the dotfiles repository and replace it with a symlink.

# invoke call for module
# {cmd} --complete module

set -e

if [[ "$_DEV_COMPLETE" == "true" ]]; then
  if [[ "$_DEV_COMPLETE_ARG" == "module" ]]; then
    ls -1 "$DOTFILES_HOME/dotfiles"
  else
    echo "panic: Bug in sub. Invalid completion options." >&2
  fi

  exit 0
fi

module="$1"
file="$2"

path="$(realpath "$file")"
path="${path#$HOME/}"

# create path where the file should go
dirpath=${path%/*}
mkdir -p "$DOTFILES_HOME/dotfiles/$module/$dirpath"

# copy file to dotfiles
cp "$file" "$DOTFILES_HOME/dotfiles/$module/$path"

# remove original file
rm "$file"

# create symlink
ln -s "$DOTFILES_HOME/dotfiles/$module/$path" "$file"
