#!/usr/bin/env bash
#
# Summary: Go to next meeting
#
# Usage: {cmd}
#
# Turns on the second monitor and opens a browser window with Google Meet.

set -e

dev dual-monitor
qutebrowser ":open -w meet.google.com"

sleep 1

awesome-client << LUA
  local awful = require("awful")

  local meet_window = function (c)
    return awful.rules.match(c, { name = "Google Meet - qutebrowser"})
  end

  for c in awful.client.iterate(meet_window) do
    c:move_to_screen()
  end
LUA
