#!/usr/bin/env bash
#
# Summary: Open tmux session for notes
#
# Usage: {cmd}
#
# Changes into the notes directory and opens a tmux session named "notes".
# This session uses a different socket name in order to separate it from all other tmux sessions.

set -e

# Configuration
name="notes"
socket_name="notes"

# Switch to session if it already exists
if tmux -L "$socket_name" has-session -t "$name" 2>/dev/null; then
  tmux -L "$socket_name" attach-session -t "$name"
  exit
fi

# Change into notes directory
cd "$HOME/Sync/notes"

# Include runtime tmux functions
source "${_DEV_ROOT}/lib/tmux.sh"

# Create tmux session
if initialize_session "$name" "$socket_name"; then
  source ".config/dev-session"
fi

finalize_and_go_to_session
