#!/usr/bin/env bash
#
# Summary: Push and open a pull request for current branch
#
# Usage: {cmd} [<base>]
#
# If <base> is not passed, it'll be detected automatically in this order of
# priority: develop -> main -> master
#
# A label 'ai assisted' will be added to the PR

set -e

base="$1"

if [ -z "$base" ]; then
  if git rev-parse --verify "origin/develop" &>/dev/null; then
    base="develop"
  elif git rev-parse --verify "origin/main" &>/dev/null; then
    base="main"
  else
    base="master"
  fi
fi

git push -u origin HEAD

hub pull-request --browse -b "$base" -l 'ai assisted'
