#!/usr/bin/env bash
#
# Summary: Push and open a pull request for current branch
#
# Usage: {cmd} [--draft] [base]
#
# If `base` is not passed, it'll be detected automatically in this order of
# priority: develop -> main -> master

set -e

declare -A args="($_DEV_ARGS)"

base="${args[base]}"
draft="${args[draft]}"

if [ -z "$base" ]; then
  if git rev-parse --verify "origin/develop" &>/dev/null; then
    base="develop"
  elif git rev-parse --verify "origin/main" &>/dev/null; then
    base="main"
  else
    base="master"
  fi
fi

git push -u origin HEAD

hub pull-request --browse -b "$base" "${draft:+--draft}"
