#!/usr/bin/env bash
#
# Summary: Push and open a pull request for current branch
#
# Usage: {cmd} [--draft] [base]
#
# If `base` is not passed, it'll be detected automatically in this order of
# priority: main -> master

set -e

declare -A args="($_DEV_ARGS)"

base="${args[base]}"
draft="${args[draft]}"

if [ -z "$base" ]; then
  if git rev-parse --verify "origin/main" &>/dev/null; then
    base="main"
  else
    base="master"
  fi
fi

git push -u origin HEAD

# Set options to --draft if draft is "true", otherwise keep it empty
options=""
if [ "$draft" = "true" ]; then
  options="--draft"
fi

hub pull-request --browse -b "$base" $options
