#!/usr/bin/env bash
#
# Summary: Shows a nice preview for a project
#
# Usage: {cmd} <project>
#
# Displays a markdown preview the project README.

set -e

# Provide completions
if [ "$1" = "--complete" ]; then
  dev list
  exit
fi

project="$1"

# determine README file for project
readme_file="$WORKSPACE/$project/README.md"

if [ -f "$readme_file" ]; then
  # display the README.md file in the project directory
  glow -s auto "$WORKSPACE/$project/README.md"
else
  echo "No README.md file found in $project"
fi

