#!/usr/bin/env bash
#
# Summary: Sets up the current repository for reviewing a PR
#
# Usage: {cmd} [<pull-request>]
#
# A pull request can be supplied as argument in any of the following formats:
#
# - by number, e.g. "123";
# - by URL, e.g. "https://github.com/OWNER/REPO/pull/123"; or
# - by the name of its head branch, e.g. "patch-1" or "OWNER:patch-1".
#
# If no argument is provided, a list of open PRs for the current repository is
# presented in a fuzzy finder.

set -e

pr="$1"

if [ -z "$pr" ]; then
  pr="$(gh pr list | sk | awk -F '\t' '{print $1}')"
fi

git fetch --all --prune --tags
gh pr checkout "$pr"

if git rev-parse --verify "origin/develop" &>/dev/null; then
  branch="origin/develop"
else
  branch="origin/master"
fi

dev stat
