#!/usr/bin/env bash
#
# Summary: Sets up the current repository for reviewing a PR
#
# Usage: {cmd} [<pull-request-id>]
#
# If no argument is provided, a list of open PRs for the current repository is
# presented in a fuzzy finder.

set -e

pr="$1"

if [ -z "$pr" ]; then
  pr="$(gh pr list | column -s $'\t' -t | sk | awk '{print $1}')"
fi

if [ -z "$pr" ]; then
  exit 1
fi

git fetch --all --prune --tags
gh pr checkout "$pr"

# Save Pull Request ID to a temporary location for other commands
echo "$pr" > .git/PULL_REQUEST_ID

if git rev-parse --verify "origin/develop" &>/dev/null; then
  branch="origin/develop"
else
  branch="origin/master"
fi

dev stat
