#!/usr/bin/env bash
#
# Summary: Sets up the current repository for reviewing a PR
#
# Usage: {cmd} [pull-request-id]
#
# If no argument is provided, a list of open PRs for the current repository is
# presented in a fuzzy finder.

set -e

pr="$1"

if [ -z "$pr" ]; then
  pr="$(gh pr list | column -s $'\t' -t | sk | awk '{print $1}')"
fi

if [ -z "$pr" ]; then
  exit 1
fi

eval "$(http --auth $GITHUB_USER:$GITHUB_TOKEN GET "https://api.github.com/repos/$(dev github repo)/pulls/${pr}" | jq -r '@sh "state=\(.state) title=\(.title) body=\(.body) head_ref=\(.head.ref) base_ref=\(.base.ref) base_sha=\(.base.sha)"')"

git fetch --all --prune --tags
git checkout "${head_ref}"
git pull --rebase

# Save Pull Request ID to a temporary location for other commands
echo "$pr" > .git/PULL_REQUEST_ID

# Print PR summary
echo
echo "#${pr} ($state)"
echo "${head_ref} -> ${base_ref}"
echo
echo "$title"
echo
echo "$body"

# Print diff
git diff --stat ${base_sha}..${head_ref}
