#!/usr/bin/env bash
#
# Summary: Take a screenshot
#
# Select a window or area to screenshot and copy it to the clipboard.

set -e

if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
    sel=$(slurp)
    grim -g "$sel" - | wl-copy
elif [ "$XDG_SESSION_TYPE" = "x11" ]; then
    sel=$(slop -f "-i %i -g %g")
    shotgun $sel - | xclip -t 'image/png' -selection clipboard
else
    echo "Unsupported session type: $XDG_SESSION_TYPE"
    exit 1
fi
