#!/usr/bin/env bash
#
# Summary: Starts development in a project
#
# Usage: {cmd} <url>
#
# Clone a project locally and start a development session for it.

set -e

url="$1"

cd $HOME/development
hub clone "$url"

project=${url##*/}
dev open "${project#*/}"
