#!/usr/bin/env bash
#
# Summary: Update all local repos from remote
#
# This runs a `git pull --rebase` on all local projects which don't have local
# changes.

cd "$WORKSPACE"

update() {
  dir="$1"

  (
    # Change into project directory
    cd $dir

    # Pull is working directory is clean
    if [ -z "$(git status --porcelain)" ]; then
      echo "=====> Working directory clean, pulling"
      git pull --rebase
    fi
  )
}
# Export this function so it can be used in a subshell by `parallel`
export -f update

# Run update on each project
(for dir in */*; do
  echo "$dir"
done) | parallel update
