#!/usr/bin/env bash
#
# Summary: Update all local repos from remote
#
# This runs a `git pull --rebase` on all local projects which don't have local
# changes.

cd "$HOME/development"

for dir in */; do
  echo "=====> Checking $dir"
  (
    cd $dir

    if [ -z "$(git status --porcelain)" ]; then
      echo "=====> Working directory clean, pulling"
      git pull --rebase
    fi
  )
done
